<a href="https://colab.research.google.com/github/inesluparia/ML/blob/master/DemocratsPredictionNAND.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import optimizers

In [ ]:
model = Sequential()
model.add(Dense(6, input_dim=6, activation='relu'))
model.add(Dense(3, activation='relu'))
adam = optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error', optimizer=adam)

In [ ]:
x = np.array([
  [0.27, 0.24, 1, 1, 0, 0],  
  [0.48, 0.98, -1, 0, 1, 0],
  [0.33, 0.44, 1, 0, 0, 1],
  [0.30, 0.29, 1, 0, 1, 0],
  [0.66, 0.65, -1, 1, 0, 0]])	
y = np.array([[1,0,0],[0,1,0],[0,1,0],[0,0,1],[1,0,0]])

In [ ]:
print(y)

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


In [ ]:
history = model.fit(x,y,epochs=1000, batch_size=6, verbose=1)

In [ ]:
prediction = model.predict([[0.38,0.51, -1, 1, 0, 0]])
print(prediction)

[[0.82321185 0.         0.        ]]


IT'S A DEMOCRAT!